# Generated by Django 4.2.3 on 2023-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='picture',
            field=models.ImageField(blank=True, upload_to='my_picture'),
        ),
    ]
