# Generated by Django 4.2.3 on 2023-07-13 12:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_file_date_added_remove_file_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(blank=True, upload_to=api.models.File.nameFile),
        ),
    ]
