# Generated by Django 4.2.3 on 2023-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_file_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Description',
            field=models.CharField(default='Write your description here', max_length=200),
        ),
    ]
