# Generated by Django 4.2.3 on 2023-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_location_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='locationName',
        ),
        migrations.AddField(
            model_name='location',
            name='Status',
            field=models.CharField(default='Yes/No', max_length=5),
        ),
        migrations.AddField(
            model_name='location',
            name='Title',
            field=models.CharField(default='Enter your Title', max_length=25, unique=True),
        ),
    ]
