# Generated by Django 4.2.3 on 2023-07-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_location_locationname_location_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Title',
            field=models.CharField(default='Enter your Title', max_length=25),
        ),
    ]
