# Generated by Django 4.2.3 on 2023-07-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_location_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Status',
        ),
    ]
