# Generated by Django 4.2.3 on 2023-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_location_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Description',
        ),
        migrations.AlterField(
            model_name='location',
            name='Title',
            field=models.CharField(default='Enter your Title', max_length=25, unique=True),
        ),
    ]
