# Generated by Django 4.2.3 on 2023-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_location_description_alter_location_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Description',
            field=models.CharField(default='Enter your Description Here', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='Status',
            field=models.CharField(default='Yes/No', max_length=5),
        ),
    ]
