# Generated by Django 4.2.3 on 2023-07-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_location_description_location_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='fileName',
            new_name='FolderName',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='fileLocation',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemLocation',
            new_name='Task',
        ),
        migrations.AlterField(
            model_name='location',
            name='Description',
            field=models.CharField(default='Enter your Task Description:', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='Title',
            field=models.CharField(default='Enter the Task Title:', max_length=25, unique=True),
        ),
    ]
